### Imbalanced Dataset

A Dataset with an unequal class distribution

In [1]:
# importing the required libraries
import numpy as np
import pandas as pd

In [2]:
# load the dataset
credit_Card_data = pd.read_csv("DataSets/credit_data.csv")

In [3]:
credit_Card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
# distribution of the two classes
credit_Card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This is Highly Imbalanced Dataset

0 --> Legit Transactions

1 --> Fraudulent Transactions

In [7]:
# separating the legit and fraudulent transactions
legit = credit_Card_data[credit_Card_data.Class == 0]
fraud = credit_Card_data[credit_Card_data.Class == 1]

In [8]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

Under-sampling

Build a sample dataset containing similar distribution of Legit & Fraudulent Transactionds

Number of Fraudulent Transactions --> 492

In [9]:
legit_sample = legit.sample(n=492)

In [10]:
print(legit_sample.shape)

(492, 31)

In [11]:
new_dataset = pd.concat([legit_sample, fraud], axis = 0)

In [12]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
105801,69696.0,-0.509915,0.921708,1.635321,-0.145950,0.031306,-0.234870,0.487219,0.236535,-0.592546,...,-0.142504,-0.373094,0.021889,0.190762,-0.342829,0.072647,0.275508,0.108186,0.89,0
94538,64934.0,1.173357,0.486647,-0.527614,1.125974,0.328124,-0.304156,0.001633,0.164012,-0.058024,...,-0.030796,-0.103749,-0.125411,-0.491118,0.570845,-0.288722,0.035661,0.036697,1.00,0
207196,136562.0,-0.406432,-0.031807,1.279092,1.245104,0.139580,-0.437479,-0.376011,-0.044074,0.044570,...,-0.101170,-0.083531,0.110373,-0.059723,-1.392995,0.512184,0.196014,0.215843,35.86,0
230727,146452.0,-0.738195,1.136009,-1.807595,-0.660933,1.180994,-0.952119,0.600929,0.452293,-0.771655,...,0.249549,0.519638,-0.325518,0.185918,0.011561,0.593423,-0.318333,-0.157959,0.76,0
115795,74020.0,-0.634424,1.202027,1.205861,0.043210,0.027458,-0.969897,0.731938,-0.166097,-0.286777,...,-0.239613,-0.665527,0.055343,0.333220,-0.159585,0.049495,-0.003779,0.080447,9.47,0

In [13]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [14]:
new_dataset.shape

(984, 31)

In [15]:
new_dataset["Class"].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [ ]:
# see this dataset rows like index rendom values 
new_dataset[new_dataset.Class == 0]

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
105801,69696.0,-0.509915,0.921708,1.635321,-0.145950,0.031306,-0.234870,0.487219,0.236535,-0.592546,...,-0.142504,-0.373094,0.021889,0.190762,-0.342829,0.072647,0.275508,0.108186,0.89,0
94538,64934.0,1.173357,0.486647,-0.527614,1.125974,0.328124,-0.304156,0.001633,0.164012,-0.058024,...,-0.030796,-0.103749,-0.125411,-0.491118,0.570845,-0.288722,0.035661,0.036697,1.00,0
207196,136562.0,-0.406432,-0.031807,1.279092,1.245104,0.139580,-0.437479,-0.376011,-0.044074,0.044570,...,-0.101170,-0.083531,0.110373,-0.059723,-1.392995,0.512184,0.196014,0.215843,35.86,0
230727,146452.0,-0.738195,1.136009,-1.807595,-0.660933,1.180994,-0.952119,0.600929,0.452293,-0.771655,...,0.249549,0.519638,-0.325518,0.185918,0.011561,0.593423,-0.318333,-0.157959,0.76,0
115795,74020.0,-0.634424,1.202027,1.205861,0.043210,0.027458,-0.969897,0.731938,-0.166097,-0.286777,...,-0.239613,-0.665527,0.055343,0.333220,-0.159585,0.049495,-0.003779,0.080447,9.47,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95600,65387.0,-0.543476,1.265490,0.726842,0.418152,-1.061204,-0.121749,-2.142459,-5.252925,-0.505441,...,-2.789308,-0.175065,0.372651,0.612490,0.528470,0.119240,-0.072985,0.199264,1.98,0
63771,50861.0,-2.683527,0.709484,1.036415,1.661385,-0.693109,0.907512,-1.361531,1.591243,0.561024,...,-0.368098,-0.623796,-0.527912,-0.268771,-0.114433,-0.407714,0.000859,-0.497907,22.48,0
69394,53402.0,-0.174395,0.770546,0.671354,0.679041,2.624379,4.080331,0.022566,0.862285,-0.945099,...,-0.037190,-0.155188,-0.004229,0.959236,-0.722525,-0.302671,0.023180,-0.033519,6.40,0
156279,107729.0,-1.000249,1.820500,-1.829965,-0.329663,1.103503,-0.597599,0.764665,0.299661,0.768982,...,0.180555,0.730276,-0.258361,0.049101,-0.245938,-0.216586,-0.183213,0.104305,18.94,0
227063,144920.0,1.009431,-1.107448,0.009608,-0.748482,-1.428861,0.471630,-0.841013,0.107848,-2.034144,...,0.106609,0.677894,0.589632,0.681277,-1.537071,0.018840,0.179941,0.093316,114.00,0